dcc: Fix unused display_channel variable
Avoid problem when compiling with lz4 and without COMPRESS_STAT

dcc.c: In function 'dcc_compress_image_lz4':
dcc.c:657:21: error: unused variable 'display_channel' [-Werror=unused-variable]
     DisplayChannel *display_channel = DCC_TO_DC(dcc);

Acked-by: Frediano Ziglio <fziglio@redhat.com>