spice-common submodule: update url (add .git at the end)
With the move to gitlab.freedesktop.org the spice-common submodule
url changed, and now ends with .git

Update .gitmodules to reflect that.

Without this patch git submodule update (and ./autogen.sh)
fails on RHEL-7 (git version 1.8.3).
On Fedora 28 (git version 2.17.1) it succeeds as it's successfully
redirecting to spice-common.git url.

With git version 1.8.3:
$ git submodule update
Cloning into 'spice-common'...
error: RPC failed; result=22, HTTP code = 404
fatal: The remote end hung up unexpectedly
Clone of 'https://gitlab.freedesktop.org/spice/spice-common' into submodule path 'spice-common' failed

Signed-off-by: Uri Lublin <uril@redhat.com>
Acked-by: Christophe Fergeau <cfergeau@redhat.com>