glz: WindowImageSegment lines lines_end as void*
Instead of using uint8_t* which can cause several warnings on casting as
the example below:

./glz_encode_tmpl.c:321:29: error: cast from 'uint8_t *'
(aka 'unsigned char *') to 'rgb16_pixel_t *' (aka 'unsigned short *')
increases required alignment from 1 to 2 [-Werror,-Wcast-align]
 ref_limit = (PIXEL *)(seg->lines_end);
              ^~~~~~~~~~~~~~~~~~~~~~~~~