ci: Fix compiling of some functions
Address sanitizer use a larger stack than normal compiled programs
making the build fails. This causes this error on GitLab CI system:

stream-device.c: In function 'stream_device_partial_read':
stream-device.c:182:1: error: the frame size of 32992 bytes is larger than 20460 bytes [-Werror=frame-larger-than=]

Allow larger stack on "makecheck" to avoid this issue.

Signed-off-by: Frediano Ziglio <fziglio@redhat.com>
Acked-by: Christophe Fergeau <cfergeau@redhat.com>